os: linux
jobs:
  include:
    - dist: xenial
      virt: vm
      language: c
      arch: 
        - mysql
        - postgresql
        - redis-server
      
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
